// Code generated by tgcon; DO NOT EDIT.
package storage

const (

	// --------------------  File: access.go  --------------------
	// Struct: Access
	AccessEmailDb    = "email"
	AccessIDDb       = "id"
	AccessIDClientDb = "id_client"
	AccessOAuthDb    = "oauth"
	AccessPasswordDb = "password"

	// --------------------  File: address.go  --------------------
	// Struct: Address
	AddressCityDb       = "city"
	AddressCountryDb    = "country"
	AddressDoorNumberDb = "door_number"
	AddressIDDb         = "id"
	AddressIDClientDb   = "id_client"
	AddressStreetDb     = "street"
	AddressZipCodeDb    = "zip_code"

	// ---------------------  File: cart.go  ---------------------
	// Struct: Cart
	CartIDClientDb = "id_client"
	CartIDGameDb   = "id_game"

	// --------------------  File: client.go  --------------------
	// Struct: Client
	ClientActiveDb      = "active"
	ClientBirthdateDb   = "birthdate"
	ClientIDDb          = "id"
	ClientNameDb        = "name"
	ClientPhoneNumberDb = "phone_number"
	ClientPictureDb     = "picture"
	ClientSurnameDb     = "surname"
	ClientVatIDDb       = "vat_id"

	// -------------  File: client_search_history.go  -------------
	// Struct: ClientSearchHistory
	ClientSearchHistoryDateTimeDb = "date_time"
	ClientSearchHistoryIDDb       = "id"
	ClientSearchHistoryIDClientDb = "id_client"
	ClientSearchHistoryIDGameDb   = "id_game"

	// ---------------------  File: game.go  ---------------------
	// Struct: Game
	GameCoverImageDb   = "cover_image"
	GameDescriptionDb  = "description"
	GameDiscountDb     = "discount"
	GameDownloadLinkDb = "download_link"
	GameIDDb           = "id"
	GameIDPublisherDb  = "id_publisher"
	GameNameDb         = "name"
	GamePriceDb        = "price"
	GameReleaseDateDb  = "release_date"
	GameStateDb        = "state"

	// -----------------  File: game_library.go  -----------------
	// Struct: GameLibrary
	GameLibraryIDClientDb = "id_client"
	GameLibraryIDGameDb   = "id_game"

	// ------------------  File: image_game.go  ------------------
	// Struct: ImageGame
	ImageGameIDDb     = "id"
	ImageGameIDGameDb = "id_game"
	ImageGameImageDb  = "image"

	// -----------------  File: invoice_game.go  -----------------
	// Struct: InvoiceGame
	InvoiceGameDiscountDb  = "discount"
	InvoiceGameIDGameDb    = "id_game"
	InvoiceGameIDInvoiceDb = "id_invoice"
	InvoiceGamePriceDb     = "price"

	// ----------------  File: invoice_header.go  ----------------
	// Struct: InvoiceHeader
	InvoiceHeaderIDClientDb     = "id_client"
	InvoiceHeaderIDInvoiceDb    = "id_invoice"
	InvoiceHeaderPurchaseDateDb = "purchase_date"
	InvoiceHeaderVatIDDb        = "vat_id"

	// ------------------  File: newsletter.go  ------------------
	// Struct: Newsletter
	NewsletterEmailDb = "email"

	// -------------------  File: publisher.go  -------------------
	// Struct: Publisher
	PublisherCoverImageDb  = "cover_image"
	PublisherEmailDb       = "email"
	PublisherIDDb          = "id"
	PublisherNameDb        = "name"
	PublisherPhoneNumberDb = "phone_number"

	// --------------------  File: review.go  --------------------
	// Struct: Review
	ReviewIDDb       = "id"
	ReviewIDClientDb = "id_client"
	ReviewIDGameDb   = "id_game"
	ReviewReviewDb   = "review"
	ReviewStarsDb    = "stars"

	// ----------------------  File: tag.go  ----------------------
	// Struct: Tag
	TagIDDb   = "id"
	TagNameDb = "name"

	// -------------------  File: tag_game.go  -------------------
	// Struct: TagGame
	TagGameIDGameDb = "id_game"
	TagGameIDTagDb  = "id_tag"

	// --------------------  File: wallet.go  --------------------
	// Struct: Wallet
	WalletBalanceDb  = "balance"
	WalletCoinDb     = "coin"
	WalletIDDb       = "id"
	WalletIDClientDb = "id_client"

	// -------------------  File: wishlist.go  -------------------
	// Struct: Wishlist
	WishlistIDClientDb = "id_client"
	WishlistIDGameDb   = "id_game"
)
