// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for GameSchemaState.
const (
	GameSchemaStateActive GameSchemaState = "active"

	GameSchemaStateInactive GameSchemaState = "inactive"

	GameSchemaStateUpcoming GameSchemaState = "upcoming"
)

// ClientAccessSchema defines model for ClientAccessSchema.
type ClientAccessSchema struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        *string   `json:"id,omitempty"`
	IdClient  *string   `json:"id_client,omitempty"`
	Oauth     bool      `json:"oauth"`
	Password  *string   `json:"password,omitempty"`
}

// ClientAddressSchema defines model for ClientAddressSchema.
type ClientAddressSchema struct {
	City       string  `json:"city"`
	Country    string  `json:"country"`
	DoorNumber *string `json:"door_number,omitempty"`
	Id         *string `json:"id,omitempty"`
	IdClient   *string `json:"id_client,omitempty"`
	Street     string  `json:"street"`
	ZipCode    string  `json:"zip_code"`
}

// ClientSchema defines model for ClientSchema.
type ClientSchema struct {
	Active      bool               `json:"active"`
	Birthdate   openapi_types.Date `json:"birthdate"`
	Id          *string            `json:"id,omitempty"`
	Name        string             `json:"name"`
	PhoneNumber string             `json:"phone_number"`
	Picture     string             `json:"picture"`
	Surname     string             `json:"surname"`
	VatId       int                `json:"vat_id"`
}

// ClientWalletSchema defines model for ClientWalletSchema.
type ClientWalletSchema struct {
	Balance  float64 `json:"balance"`
	Coin     []byte  `json:"coin"`
	Id       *string `json:"id,omitempty"`
	IdClient *string `json:"id_client,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	Error string `json:"error"`
}

// GameImageSchema defines model for GameImageSchema.
type GameImageSchema struct {
	Id     string `json:"id"`
	IdGame string `json:"id_game"`
	Image  string `json:"image"`
}

// GameSchema defines model for GameSchema.
type GameSchema struct {
	CoverImage   string             `json:"cover_image"`
	Description  string             `json:"description"`
	Discount     float64            `json:"discount"`
	DownloadLink string             `json:"download_link"`
	Id           *string            `json:"id,omitempty"`
	IdPublisher  string             `json:"id_publisher"`
	Name         string             `json:"name"`
	Price        float64            `json:"price"`
	ReleaseDate  openapi_types.Date `json:"release_date"`
	State        GameSchemaState    `json:"state"`
}

// GameSchemaState defines model for GameSchema.State.
type GameSchemaState string

// InvoiceSchema defines model for InvoiceSchema.
type InvoiceSchema struct {
	Games []struct {
		Discount float64 `json:"discount"`
		IdGame   string  `json:"id_game"`
		Price    float64 `json:"price"`
	} `json:"games"`
	Id           string    `json:"id"`
	IdClient     string    `json:"id_client"`
	PurchaseDate time.Time `json:"purchase_date"`
	VatId        int       `json:"vat_id"`
}

// NewStoreSchema defines model for NewStoreSchema.
type NewStoreSchema struct {
	Featured []GameSchema `json:"featured"`
	New      []GameSchema `json:"new"`
}

// NewsletterSchema defines model for NewsletterSchema.
type NewsletterSchema struct {
	Email string `json:"email"`
}

// NoteworthyStoreSchema defines model for NoteworthyStoreSchema.
type NoteworthyStoreSchema struct {
	Featured   []GameSchema `json:"featured"`
	Noteworthy []GameSchema `json:"noteworthy"`
}

// PublisherSchema defines model for PublisherSchema.
type PublisherSchema struct {
	CoverImage  string  `json:"cover_image"`
	Email       string  `json:"email"`
	Id          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	PhoneNumber string  `json:"phone_number"`
}

// ReviewSchema defines model for ReviewSchema.
type ReviewSchema struct {
	Id       *string `json:"id,omitempty"`
	IdClient *string `json:"id_client,omitempty"`
	IdGame   *string `json:"id_game,omitempty"`
	Review   *string `json:"review,omitempty"`
	Stars    *int    `json:"stars,omitempty"`
}

// SearchSchema defines model for SearchSchema.
type SearchSchema struct {
	DateTime time.Time `json:"date_time"`
	Id       string    `json:"id"`
	IdClient string    `json:"id_client"`
	IdGame   string    `json:"id_game"`
}

// TagSchema defines model for TagSchema.
type TagSchema struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

// VersionSchema defines model for VersionSchema.
type VersionSchema struct {
	Notes   string `json:"notes"`
	Version string `json:"version"`
}

// YourStoreSchema defines model for YourStoreSchema.
type YourStoreSchema struct {
	Discover      []GameSchema `json:"discover"`
	Featured      []GameSchema `json:"featured"`
	Recommended   []GameSchema `json:"recommended"`
	SpecialOffers []GameSchema `json:"specialOffers"`
}

// PutAccessJSONBody defines parameters for PutAccess.
type PutAccessJSONBody ClientAccessSchema

// PutAccessParams defines parameters for PutAccess.
type PutAccessParams struct {
	// Client ID
	ClientID string `json:"clientID"`
}

// GetAddBalanceParams defines parameters for GetAddBalance.
type GetAddBalanceParams struct {
	// Client ID
	Id string `json:"id"`

	// Amount to add
	Amount float64 `json:"amount"`
}

// GetAddressParams defines parameters for GetAddress.
type GetAddressParams struct {
	// Client ID
	Id string `json:"id"`
}

// PutAddressJSONBody defines parameters for PutAddress.
type PutAddressJSONBody ClientAddressSchema

// PutAddressParams defines parameters for PutAddress.
type PutAddressParams struct {
	// Address ID
	Id string `json:"id"`
}

// DeleteCartParams defines parameters for DeleteCart.
type DeleteCartParams struct {
	// Client ID
	ClientID string `json:"clientID"`

	// Game ID
	GameID *string `json:"gameID,omitempty"`
}

// GetCartParams defines parameters for GetCart.
type GetCartParams struct {
	// Client ID
	Id string `json:"id"`
}

// PostCartParams defines parameters for PostCart.
type PostCartParams struct {
	// Client ID
	ClientID string `json:"clientID"`

	// Game ID
	GameID string `json:"gameID"`
}

// GetCartPurchaseParams defines parameters for GetCartPurchase.
type GetCartPurchaseParams struct {
	// Client ID
	Id string `json:"id"`
}

// DeleteClientParams defines parameters for DeleteClient.
type DeleteClientParams struct {
	// Client ID
	Id string `json:"id"`
}

// GetClientParams defines parameters for GetClient.
type GetClientParams struct {
	// Client ID
	Id *string `json:"id,omitempty"`
}

// PutClientJSONBody defines parameters for PutClient.
type PutClientJSONBody ClientSchema

// PutClientParams defines parameters for PutClient.
type PutClientParams struct {
	// Client ID
	Id string `json:"id"`
}

// DeleteGameParams defines parameters for DeleteGame.
type DeleteGameParams struct {
	// Game ID
	Id string `json:"id"`
}

// GetGameParams defines parameters for GetGame.
type GetGameParams struct {
	// Game ID
	Id *string `json:"id,omitempty"`
}

// PostGameJSONBody defines parameters for PostGame.
type PostGameJSONBody GameSchema

// PutGameJSONBody defines parameters for PutGame.
type PutGameJSONBody GameSchema

// PutGameParams defines parameters for PutGame.
type PutGameParams struct {
	// Game ID
	Id string `json:"id"`
}

// DeleteGameImageParams defines parameters for DeleteGameImage.
type DeleteGameImageParams struct {
	// Image ID
	Id string `json:"id"`
}

// GetGameImageParams defines parameters for GetGameImage.
type GetGameImageParams struct {
	// Game ID
	Id string `json:"id"`
}

// PostGameImageParams defines parameters for PostGameImage.
type PostGameImageParams struct {
	// Game ID
	GameID string `json:"gameID"`

	// Image URL
	Image string `json:"image"`
}

// GetGameReviewsParams defines parameters for GetGameReviews.
type GetGameReviewsParams struct {
	// Game ID
	Id string `json:"id"`
}

// DeleteGameTagParams defines parameters for DeleteGameTag.
type DeleteGameTagParams struct {
	// Game ID
	GameID string `json:"gameID"`

	// Tag ID
	TagID string `json:"tagID"`
}

// GetGameTagParams defines parameters for GetGameTag.
type GetGameTagParams struct {
	// Game ID
	Id string `json:"id"`
}

// PostGameTagParams defines parameters for PostGameTag.
type PostGameTagParams struct {
	// Game ID
	GameID string `json:"gameID"`

	// Tag ID
	TagID string `json:"tagID"`
}

// GetInvoiceParams defines parameters for GetInvoice.
type GetInvoiceParams struct {
	// Client ID
	Id string `json:"id"`
}

// GetLibraryParams defines parameters for GetLibrary.
type GetLibraryParams struct {
	// Client ID
	Id string `json:"id"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody ClientAccessSchema

// GetNewStoreParams defines parameters for GetNewStore.
type GetNewStoreParams struct {
	// Tag ids
	Ids *[]string `json:"ids,omitempty"`
}

// DeleteNewsletterParams defines parameters for DeleteNewsletter.
type DeleteNewsletterParams struct {
	// Email to unsubscribe
	Email string `json:"email"`
}

// PostNewsletterParams defines parameters for PostNewsletter.
type PostNewsletterParams struct {
	// Email to subscribe
	Email string `json:"email"`
}

// GetNoteworthyStoreParams defines parameters for GetNoteworthyStore.
type GetNoteworthyStoreParams struct {
	// Tag ids
	Ids *[]string `json:"ids,omitempty"`
}

// DeletePublisherParams defines parameters for DeletePublisher.
type DeletePublisherParams struct {
	// Publisher ID
	Id string `json:"id"`
}

// GetPublisherParams defines parameters for GetPublisher.
type GetPublisherParams struct {
	// Publisher ID
	Id *string `json:"id,omitempty"`
}

// PostPublisherJSONBody defines parameters for PostPublisher.
type PostPublisherJSONBody PublisherSchema

// PutPublisherJSONBody defines parameters for PutPublisher.
type PutPublisherJSONBody PublisherSchema

// PutPublisherParams defines parameters for PutPublisher.
type PutPublisherParams struct {
	// Publisher ID
	Id string `json:"id"`
}

// GetPublisherGamesParams defines parameters for GetPublisherGames.
type GetPublisherGamesParams struct {
	// Publisher ID
	Id string `json:"id"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody ClientAccessSchema

// DeleteReviewParams defines parameters for DeleteReview.
type DeleteReviewParams struct {
	// Review ID
	Id string `json:"id"`
}

// PostReviewJSONBody defines parameters for PostReview.
type PostReviewJSONBody ReviewSchema

// PutReviewJSONBody defines parameters for PutReview.
type PutReviewJSONBody ReviewSchema

// PutReviewParams defines parameters for PutReview.
type PutReviewParams struct {
	// Review ID
	Id string `json:"id"`
}

// GetSearchGameParams defines parameters for GetSearchGame.
type GetSearchGameParams struct {
	// Search query
	Search string `json:"search"`
}

// GetSearchHistoryParams defines parameters for GetSearchHistory.
type GetSearchHistoryParams struct {
	// Client ID
	Id string `json:"id"`
}

// PostSearchHistoryParams defines parameters for PostSearchHistory.
type PostSearchHistoryParams struct {
	// Client ID
	ClientID string `json:"clientID"`

	// Game ID
	GameID string `json:"gameID"`
}

// GetSearchTagParams defines parameters for GetSearchTag.
type GetSearchTagParams struct {
	// Search query
	Search string `json:"search"`
}

// DeleteTagParams defines parameters for DeleteTag.
type DeleteTagParams struct {
	// Tag ID
	Id string `json:"id"`
}

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	// Tag ID
	Id *string `json:"id,omitempty"`
}

// PostTagJSONBody defines parameters for PostTag.
type PostTagJSONBody TagSchema

// PutTagJSONBody defines parameters for PutTag.
type PutTagJSONBody TagSchema

// PutTagParams defines parameters for PutTag.
type PutTagParams struct {
	// Tag ID
	Id string `json:"id"`
}

// GetWalletParams defines parameters for GetWallet.
type GetWalletParams struct {
	// Client ID
	Id string `json:"id"`
}

// PutWalletJSONBody defines parameters for PutWallet.
type PutWalletJSONBody ClientWalletSchema

// PutWalletParams defines parameters for PutWallet.
type PutWalletParams struct {
	// Wallet ID
	Id string `json:"id"`
}

// DeleteWishlistParams defines parameters for DeleteWishlist.
type DeleteWishlistParams struct {
	// Client ID
	ClientID string `json:"clientID"`

	// Game ID
	GameID *string `json:"gameID,omitempty"`
}

// GetWishlistParams defines parameters for GetWishlist.
type GetWishlistParams struct {
	// Client ID
	Id string `json:"id"`
}

// PostWishlistParams defines parameters for PostWishlist.
type PostWishlistParams struct {
	// Client ID
	ClientID string `json:"clientID"`

	// Game ID
	GameID string `json:"gameID"`
}

// GetYourStoreParams defines parameters for GetYourStore.
type GetYourStoreParams struct {
	// Client ID
	Id string `json:"id"`
}

// PutAccessJSONRequestBody defines body for PutAccess for application/json ContentType.
type PutAccessJSONRequestBody PutAccessJSONBody

// PutAddressJSONRequestBody defines body for PutAddress for application/json ContentType.
type PutAddressJSONRequestBody PutAddressJSONBody

// PutClientJSONRequestBody defines body for PutClient for application/json ContentType.
type PutClientJSONRequestBody PutClientJSONBody

// PostGameJSONRequestBody defines body for PostGame for application/json ContentType.
type PostGameJSONRequestBody PostGameJSONBody

// PutGameJSONRequestBody defines body for PutGame for application/json ContentType.
type PutGameJSONRequestBody PutGameJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostPublisherJSONRequestBody defines body for PostPublisher for application/json ContentType.
type PostPublisherJSONRequestBody PostPublisherJSONBody

// PutPublisherJSONRequestBody defines body for PutPublisher for application/json ContentType.
type PutPublisherJSONRequestBody PutPublisherJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PostReviewJSONRequestBody defines body for PostReview for application/json ContentType.
type PostReviewJSONRequestBody PostReviewJSONBody

// PutReviewJSONRequestBody defines body for PutReview for application/json ContentType.
type PutReviewJSONRequestBody PutReviewJSONBody

// PostTagJSONRequestBody defines body for PostTag for application/json ContentType.
type PostTagJSONRequestBody PostTagJSONBody

// PutTagJSONRequestBody defines body for PutTag for application/json ContentType.
type PutTagJSONRequestBody PutTagJSONBody

// PutWalletJSONRequestBody defines body for PutWallet for application/json ContentType.
type PutWalletJSONRequestBody PutWalletJSONBody

