// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package oapi

// VersionSchema defines model for VersionSchema.
type VersionSchema struct {
	Notes   string `json:"notes"`
	Version string `json:"version"`
}

