-- drop all tables 

DROP TABLE IF EXISTS "client" CASCADE;
DROP TABLE IF EXISTS "access" CASCADE;
DROP TABLE IF EXISTS "client_search_history" CASCADE;
DROP TABLE IF EXISTS "wallet" CASCADE;
DROP TABLE IF EXISTS "address" CASCADE;
DROP TABLE IF EXISTS "publisher" CASCADE;
DROP TABLE IF EXISTS "game" CASCADE;
DROP TABLE IF EXISTS "image_game" CASCADE;
DROP TABLE IF EXISTS "review" CASCADE;
DROP TABLE IF EXISTS "tag_game" CASCADE;
DROP TABLE IF EXISTS "tag" CASCADE;
DROP TABLE IF EXISTS "wishlist" CASCADE;
DROP TABLE IF EXISTS "game_library" CASCADE;
DROP TABLE IF EXISTS "cart" CASCADE;
DROP TABLE IF EXISTS "invoice_header" CASCADE;
DROP TABLE IF EXISTS "invoice_game" CASCADE;
DROP TABLE IF EXISTS "newsletter" CASCADE;

-- drop all types

DROP TYPE IF EXISTS "state_game" CASCADE;

-- drop all functions

DROP FUNCTION IF EXISTS update_created_at() CASCADE;
DROP FUNCTION IF EXISTS update_purchase_date() CASCADE;
DROP FUNCTION IF EXISTS update_date_time() CASCADE;